### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by Nubebuster**

### CODE REVIEW

**Comment by Nubebuster** [comment]
Is a player breaking a stone block supposed to get stone instead of cobblestone?

**Comment by TheRealKabo** [comment]
Adding the minimessage dependency is not required because it's already included in paper and this plugin will be paper only.

**Comment by TheRealKabo** [comment]
> Is a player breaking a stone block supposed to get stone instead of cobblestone?

For now yes. In the future, we need to build a system that allows custom blocks (like ItemsAdder).

**Review by TheRealKabo — CHANGES_REQUESTED** [review]
Remove dependency as it's not necessary

**Pull request merged**
